apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning workspace..."
        rm -rf /workspace/source/__pycache__

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-tests
      image: python:3.10
      script: |
        pip install nose
        nosetests
